import { Brain, CheckCircle2, AlertTriangle, Lightbulb } from "lucide-react";

export default function AIAnalysisCard() {
  return (
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="rounded-xl bg-violet-100 p-3">
          <Brain className="h-6 w-6 text-violet-600" />
        </div>

        <div>
          <h2 className="text-2xl font-bold text-slate-900">
            AI Resume Analysis
          </h2>

          <p className="text-slate-500">
            Personalized feedback generated by AI.
          </p>
        </div>
      </div>

      {/* Strengths */}
      <div className="mt-8">
        <h3 className="mb-4 flex items-center gap-2 font-semibold text-green-600">
          <CheckCircle2 className="h-5 w-5" />
          Strengths
        </h3>

        <ul className="space-y-3 text-sm text-slate-600">
          <li>✔ Strong React.js project experience.</li>
          <li>✔ Good academic achievements.</li>
          <li>✔ Well-structured GitHub portfolio.</li>
          <li>✔ Internship experience included.</li>
        </ul>
      </div>

      {/* Weaknesses */}
      <div className="mt-8">
        <h3 className="mb-4 flex items-center gap-2 font-semibold text-amber-600">
          <AlertTriangle className="h-5 w-5" />
          Areas to Improve
        </h3>

        <ul className="space-y-3 text-sm text-slate-600">
          <li>• Add more quantified achievements.</li>
          <li>• Include technical certifications.</li>
          <li>• Improve keyword matching.</li>
        </ul>
      </div>

      {/* Recommendation */}
      <div className="mt-8 rounded-2xl bg-blue-50 p-5">
        <div className="flex items-start gap-3">
          <Lightbulb className="mt-1 h-6 w-6 text-blue-600" />

          <div>
            <h4 className="font-semibold text-slate-900">AI Recommendation</h4>

            <p className="mt-2 text-sm text-slate-600">
              Your resume has a strong foundation. Adding measurable
              achievements, cloud technologies, and industry certifications
              could significantly improve your ATS score and increase your
              chances of receiving interview calls.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
